name: Update Tech Log

on:
  push:
    paths:
      - 'screenshots/**'
      - '.github/workflows/update-log.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Log Update Script
        run: python update_log.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update tech log" || echo "No changes to commit"
          git push
